name: Scrape Google Search Results

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        location: ['US']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4
          pip install requests

      - name: Run web scraping script
        run: python scrape_google.py ${{ matrix.location }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: warehouse-jobs
          path: output/warehouse_jobs.csv